baseurl = "https://www.bradleycarey.com"
title = "bradleycarey.com"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "vs"

disqusShortname = "bradleycarey"

[params]
    author = "Bradley Carey"
    description = "Bradley Carey's personal website"
    keywords = "blog,developer,personal,programming"
    info = "Full Stack Developer"
    avatarurl = "images/avatar.png"
    favicon_32 = "images/favicon.png"
    favicon_16 = "images/favicon.png"
    dateformat = "Jan 2, 2006"
    hideCredits = true
    hideCopyright = true
    custom_css = ["css/custom.css"]

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/avianbc/"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    weight = 2
    url = "https://stackoverflow.com/users/636942/br4d"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bradley-carey-83ba3554/"
[[params.social]]
    name = "last.fm"
    icon = "fab fa-lastfm"
    weight = 4
    url = "https://www.last.fm/user/avianbc"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 3
        url = "/contact/"
