baseurl = "http://www.bradleycarey.com"
title = "bradleycarey.com"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "bradleycarey"

[params]
    author = "Bradley Carey"
    description = "Bradley Carey's personal website"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer"
    avatarurl = "images/avatar.png"
    footercontent = "My name is Brad and I love learning new things."

    dateformat = "Jan 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/avianbc/blog/tree"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/codecolorer.css","css/custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/avianbc/"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    weight = 2
    url = "https://stackoverflow.com/users/636942/br4d"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bradley-carey-83ba3554/"
[[params.social]]
    name = "last.fm"
    icon = "fab fa-lastfm"
    weight = 4
    url = "https://www.last.fm/user/avianbc"
[[params.social]]
    name = "Soundcloud"
    icon = "fab fa-soundcloud"
    weight = 5
    url = "https://soundcloud.com/avianbc"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"
